dataset_path: YeMoKoo/MMLongBench_doc
dataset_kwargs:
  data_files: MMLongBench_Doc_valid.jsonl
task: "mmlongbench_val"
test_split: train 
output_type: generate_until
doc_to_visual: !function utils.mmlongbench_doc_to_visual
doc_to_text: !function utils.mmlongbench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  do_sample: False
process_results: !function utils.mmlongbench_process_results
metric_list:
  - metric: anls
    aggregation: !function utils.mmlongbench_aggregate_results_anls
    higher_is_better: true
  - metric: accuracy
    aggregation: !function utils.mmlongbench_aggregate_results_accuracy
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."

